###
GET http://localhost:4000/tickets/full HTTP/1.1

###

POST http://localhost:4005/tickets HTTP/1.1
content-type: application/json

{
    "description": "Test Ticket description",
    "status": "OPEN",
    "priority": 2,
    "authorId": 1,
    "internal": true
}

###
DELETE http://localhost:4000/tickets/16 HTTP/1.1


###

GET https://psa-support-sq2-api.herokuapp.com/tickets HTTP/1.1
